#!/bin/bash

# Use netstat to list all listening TCP and UDP ports along with their details
# -t: Show TCP ports
# -u: Show UDP ports
# -l: Show only listening sockets
# -n: Show numerical addresses instead of resolving hosts
# -p: Show the PID and name of the program to which each socket belongs
sudo netstat -tulnp | grep LISTEN

# Use netstat to list all listening UNIX domain sockets along with their details
# -l: Show only listening sockets
# -x: Show UNIX domain sockets
sudo netstat -lx | grep LISTEN
